fix: broken link in pNFT guide
metaplex-foundation/mpl-token-metadata pull request #37
Opened 2023-08-06 16:22 UTC by jim4067

Update broken links, to point to this ☝️ repository [Programmable NFT Guide](https://github.com/metaplex-foundation/mpl-token-metadata/blob/main/programs/token-metadata/program/ProgrammableNFTGuide.md)

2023-08-06 17:37 UTC, lorisleiva submitted a review, later dismissed
Thank you!

2023-08-07 21:17 UTC, danenbm approved these changes

2023-08-12 07:35 UTC, febo requested changes

2023-08-12 07:35 UTC, febo commented on programs/token-metadata/program/ProgrammableNFTGuide.md
> +* [x] [`Migrate`](https://github.com/metaplex-foundation/mpl-token-metadata/blob/45826f100c82bc2333116fed53f9a820a5329293/programs/token-metadata/program/src/instruction/mod.rs#L682-L6993)
The line offset does not seem correct.

2023-08-12 07:35 UTC, febo commented on programs/token-metadata/program/ProgrammableNFTGuide.md
> +* [x] [`Mint`](https://github.com/metaplex-foundation/mpl-token-metadata/blob/45826f100c82bc2333116fed53f9a820a5329293/programs/token-metadata/program/src/instruction/mod.rs#L573-L595) <span style="f
Missing the link for the `Print` instruction.

2023-09-02 21:10 UTC, febo approved these changes
Thank you!

2023-09-02 21:30 UTC, lorisleiva approved these changes

2023-09-03 08:23 UTC, merged